### PR TITLE
Implement Azure nuke

### PR DESCRIPTION
**Pull request by bharanidharan14**
Used [Azure-nuke](https://github.com/ekristen/azure-nuke) library to terminate resources in Azure.
- Added Azure nuke example DAG and config YAML file

closes: #570

### CODE REVIEW

**Comment by rajaths010494** [comment]
Add details of what nuke resource are cleaned in description.

**Comment by phanikumv** [comment]
@rajaths010494 can you please take this forward?

**Comment by rajaths010494** [comment]
yes sure @phanikumv

**Comment by phanikumv** [comment]
whats the status on this @rajaths010494 ?

**Comment by rajaths010494** [comment]
Needs to be tested .

**Pull request closed without merging**
