### PR TITLE
feat(http): check state before deferring HttpSensorAsync

### PR DESCRIPTION
**Pull request by Lee-W**

### CODE REVIEW

**Comment by Lee-W** [comment]
## providers-integration-test
image

**Comment by Lee-W** [comment]
## providers-integration-test-on-KE

image

**Review by pankajastro — APPROVED** [review]
LGTM

**Review by pankajkoti — COMMENTED** [review]
PR description missing. 

Please take a read on the following that helps write good commit messages:
https://cbea.ms/git-commit/

https://cbea.ms/git-commit/#why-not-how

**Comment by Lee-W** [comment]
Sure. I forget to add to these few last night 🤦‍♂️ 
Ok, I'll add more detail in the body. Thanks!

**Pull request merged**
