### PR TITLE
Fix response key's for SageMaker Training and Transform operator

### PR DESCRIPTION
**Pull request by bharanidharan14**
Fixed the response key for SageMaker Training and Transform Operator

closes: #736

### CODE REVIEW

**Review by phanikumv — CHANGES_REQUESTED** [review]
The title and description do not indicate what and why we are doing this change

**Review by rajaths010494 — APPROVED** [review]
LGTM . Just a question, how frequently do we want to update the session tokens with the new connection setup?

**Comment by bharanidharan14** [comment]
> LGTM . Just a question, how frequently do we want to update the session tokens with the new connection setup?

Currently, We are facing some issues on the session token which is causing some steps to fail in the integration, sill I am looking into it.

**Comment by bharanidharan14** [comment]
> > LGTM . Just a question, how frequently do we want to update the session tokens with the new connection setup?
> 
> Currently, We are facing some issues on the session token which is causing some steps to fail in the integration, sill I am looking into it.

I have fixed the issue and created the session token with credentials in this PR #739

**Comment by bharanidharan14** [comment]
@phanikumv @rajaths010494 @pankajastro can you guys review this PR

**Review by phanikumv — APPROVED** [review]

**Pull request merged**
