### PR TITLE
[DO NOT MERGE] Deprecate amazon provider

### PR DESCRIPTION
**Pull request by Lee-W**
**This is not going to be merged** I think splitting these changes into smaller PRs will be easier to review and debug. Will close it after all the changes have been sent as separate PRs

### CODE REVIEW

**Comment by phanikumv** [comment]
Please add description about why you are doing this change

**Comment by Lee-W** [comment]
> Please add description about why you are doing this change

This one is most likely not going to be used. Let me add this to the description.

**Comment by pankajkoti** [comment]
yes, smaller PRs is easier to review, thanks for separating these 👍🏽

**Review by pankajkoti — COMMENTED** [review]
yes, smaller PRs is easier to review, thanks for separating these 👍🏽

**Pull request closed without merging**
