### PR TITLE
feat(hive): check state before deferring HivePartitionSensorAsync

### PR DESCRIPTION
**Pull request by Lee-W**
Similar to [SnowflakeOperatorAsync](https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/operators/snowflake.py#L217), we want to check whether the task has finished before it's deferred. For most sensors, we have a poke method in its sync counter part which can help us do such check.

### CODE REVIEW

**Review by pankajastro — APPROVED** [review]
LGTM

**Review by pankajkoti — COMMENTED** [review]
Please add description to the PR when it's ready for review :)

Guides on writing good commit messages.
https://cbea.ms/git-commit/

https://cbea.ms/git-commit/#why-not-how

**Comment by Lee-W** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/astronomer/providers/apache/hive/sensors/hive_partition.py", line 45, in execute
    if not self.poke(context=context):
  File "/usr/local/lib/python3.10/site-packages/airflow/providers/apache/hive/sensors/hive_partition.py", line 78, in poke
    return hook.check_for_partition(self.schema, self.table, self.partition)
  File "/usr/local/lib/python3.10/site-packages/airflow/providers/apache/hive/hooks/hive.py", line 601, in check_for_partition
    partitions = client.get_partitions_by_filter(
  File "/usr/local/lib/python3.10/site-packages/hmsclient/genthrift/hive_metastore/ThriftHiveMetastore.py", line 3611, in get_partitions_by_filter
    return self.recv_get_partitions_by_filter()
  File "/usr/local/lib/python3.10/site-packages/hmsclient/genthrift/hive_metastore/ThriftHiveMetastore.py", line 3626, in recv_get_partitions_by_filter
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python3.10/site-packages/thrift/protocol/TBinaryProtocol.py", line 148, in readMessageBegin
    name = self.trans.readAll(sz)
  File "/usr/local/lib/python3.10/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.10/site-packages/thrift/transport/TTransport.py", line 164, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/usr/local/lib/python3.10/site-packages/thrift/transport/TSocket.py", line 166, in read
    raise TTransportException(type=TTransportException.END_OF_FILE,
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
```

**Comment by Lee-W** [comment]
image

**Review by pankajastro — APPROVED** [review]

**Pull request merged**
