### PR TITLE
Bump runtime image to 7.2.0

### PR DESCRIPTION
**Pull request by pankajastro**
update runtime image.
Look like yesterday while testing rc I upgraded the version

Bump runtime image to 7.2.0

### CODE REVIEW

**Comment by pankajastro** [comment]
PR https://github.com/astronomer/astronomer-providers/pull/848 will fix the CI

**Review by phanikumv — COMMENTED** [review]
should we update Makefile as well?

**Review by pankajkoti — COMMENTED** [review]
Should we create new deployments while testing RCs? 
What should be the right way as deployments most often cannot be downgraded back to stable released versions once we deploy RC images?

cc: @phanikumv

**Comment by phanikumv** [comment]
> Should we create new deployments while testing RCs? What should be the right way as deployments most often cannot be downgraded back to stable released versions once we deploy RC images?
> 
> cc: @phanikumv

yeah that's a good idea, and let's improve test-rc-deps to do that @pankajkoti

**Comment by pankajastro** [comment]
7.2.0 has been release to lets bump up the version

**Comment by pankajastro** [comment]
> I think we will need a new make target as this is for testing Runtime image changes and not provider RCs. I have created a ticket here: #851

Added my comments on above ticket

**Review by phanikumv — APPROVED** [review]

**Pull request merged**
