### PR TITLE
[DO NOT MERGE] Test RC provider packages

### PR DESCRIPTION
**Pull request by bharanidharan14**

### CODE REVIEW

**Review by pankajkoti — COMMENTED** [review]
This looks code. Can we check how we can test the Kubernetes RC ?

**Comment by phanikumv** [comment]
> This looks good. Can we check how we can test the Kubernetes RC ?

yup, we need to automate testing KPO

**Comment by bharanidharan14** [comment]
@phanikumv, Need to test it with the wheel link like we have done previously.  Got the wheel link will test it

**Comment by pankajkoti** [comment]
We tested this and found no issues. Closing.

**Pull request closed without merging**
