### PR TITLE
Deprecate s3 keys unchanged sensor async

### PR DESCRIPTION
**Pull request by Lee-W**
This PR is blocked by the release of ~~https://github.com/apache/airflow/pull/36363~~ https://github.com/apache/airflow/issues/36467

upgrade minimum apache-airflow-providers-amazon to 8.15.0 and deprecate S3KeysUnchangedSensorAsync

### CODE REVIEW

**Comment by Lee-W** [comment]
It has been tested on astro cloud with amazon == 8.15.0

**Comment by Lee-W** [comment]
It has been tested on astro cloud with amazon == 8.15.0

**Review by pankajastro — APPROVED** [review]
LGTM

**Review by pankajkoti — COMMENTED** [review]
It just struck me. We would need to remove any hook specific code too right for this and other deprecation PRs?

**Comment by Lee-W** [comment]
> It just struck me. We would need to remove any hook specific code too right for this and other deprecation PRs?

yep, let me remove it in another PR

**Comment by pankajastro** [comment]
> It just struck me. We would need to remove any hook specific code too right for this and other deprecation PRs?

sometimes people use hook implementation in taskflow API so wondering if we remove hook code then need a major release?

**Pull request merged**
