### PR TITLE
Run tests for rc

### PR DESCRIPTION
**Pull request by pankajastro**

### CODE REVIEW

**Comment by phanikumv** [comment]
closing as rc tests are complete

**Comment by pankajkoti** [comment]
@pankajastro Usually, in this RC testing PR, we try to fix the `mypy` failures in this PR making sure that both versions of providers work and see that the check runs fine. And when the provider is released, we introduce the same changes in a new PR so that we have the changes ready and can copy them from here.

cc: @rajaths010494

**Comment by rajaths010494** [comment]
> @pankajastro Usually, in this RC testing PR, we try to fix the `mypy` failures in this PR making sure that both versions of providers work and see that the check runs fine. And when the provider is released, we introduce the same changes in a new PR so that we have the changes ready and can copy them from here.
> 
> cc: @rajaths010494

yes usually we fix the mypy here.

**Comment by rajaths010494** [comment]
closing this as mypy has been fixed.

cc @pankajkoti / @pankajastro / @phanikumv

**Comment by pankajkoti** [comment]
Thanks a lot, @rajaths010494 for taking care of this. Amazing!

**Pull request closed without merging**
