### PR TITLE
[DO NOT MERGE] Test RC provider packages

### LINKED ISSUE #871: Test RC providers

### PR DESCRIPTION
**Pull request by rajaths010494**
closes #871

### CODE REVIEW

**Comment by rajaths010494** [comment]
All dags are fine and it posted on slack channel

**Review by pankajkoti — COMMENTED** [review]
@rajaths010494 mypy fixes look correct to me 👍🏽

**Comment by pankajkoti** [comment]
I think we can give our +1 votes @rajaths010494 @phanikumv @pankajastro and close this PR.

**Comment by rajaths010494** [comment]
> I think we can give our +1 votes @rajaths010494 @phanikumv @pankajastro and close this PR. I already gave one for the Google provider RC in the mail thread.

I gave my +1 non-binding

**Pull request closed without merging**
