### PR TITLE
Fix GCP Dataproc DAG failed with timeout error

### LINKED ISSUE #512: GCP Dataproc DAG failed with timeout error
For 1 instance of the DAG triggered on 14th July as part of the master DAG, the GCP Dataproc DAG has failed with below error:
```
[2022-07-14, 00:06:09 UTC] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_gcp_dataproc.create_cluster dataproc_dag_example_gcp_dataproc_2022-07-13 [queued]>
[2022-07-14, 00:06:09 UTC] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-14, 00:06:09 UTC] {taskinstance.py:1377} INFO - Starting attempt 1 of 3
[2022-07-14, 00:06:09 UTC] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-14, 00:06:09 UTC] {manager.py:53} WARNING - Unable to find an extractor. task_type=DataprocCreateClusterOperatorAsync airflow_dag_id=example_gcp_dataproc task_id=create_cluster airflow_run_id=dataproc_dag_example_gcp_dataproc_2022-07-13 
[2022-07-14, 00:06:09 UTC] {taskinstance.py:1397} INFO - Executing <Task(DataprocCreateClusterOperatorAsync): create_cluster> on 2022-07-13 00:00:00+00:00
[2022-07-14, 00:06:09 UTC] {standard_task_runner.py:52} INFO - Started process 2037 to run task
[2022-07-14, 00:06:09 UTC] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example_gcp_dataproc', 'create_cluster', 'dataproc_dag_example_gcp_dataproc_2022-07-13', '--job-id', '37788', '--raw', '--subdir', 'DAGS_FOLDER/example_dataproc.py', '--cfg-path', '/tmp/tmp8x1og6yh', '--error-file', '/tmp/tmpmkt1d28n']
[2022-07-14, 00:06:09 UTC] {standard_task_runner.py:80} INFO - Job 37788: Subtask create_cluster
[2022-07-14, 00:06:09 UTC] {task_command.py:371} INFO - Running <TaskInstance: example_gcp_dataproc.create_cluster dataproc_dag_example_gcp_dataproc_2022-07-13 [running]> on host 10.1.4.36
[2022-07-14, 00:06:09 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/google/cloud/operators/dataproc.py", line 126, in execute_complete
    raise AirflowException(event["message"])
airflow.exceptions.AirflowException: Timeout
[2022-07-14, 00:06:09 UTC] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=example_gcp_dataproc, task_id=create_cluster, execution_date=20220713T000000, start_date=20220714T000603, end_date=20220714T000609
[2022-07-14, 00:06:09 UTC] {standard_task_runner.py:92} ERROR - Failed to execute job 37788 for task create_cluster (Timeout; 2037)
[2022-07-14, 00:06:09 UTC] {local_task_job.py:156} INFO - Task exited with return code 1
```

Retriggering the DAG worked fine, but need to check what went wrong here

### PR DESCRIPTION
**Pull request by rajaths010494**
`time.monotonic()` was having a larger time than end time at times. Attaching screenshot for reference
Screenshot 2022-08-16 at 1 49 54 PM
So replacing `time.monotonic()`  with `time.time()`
Closes #512

### CODE REVIEW

**Comment by phanikumv** [comment]
Correct the title please.

**Review by pankajkoti — APPROVED** [review]
Thanks for fixing this @rajaths010494 . Looks good to me if the DAG runs all fine.

**Comment by rajaths010494** [comment]
> Correct the title please.

Changed the title

**Comment by rajaths010494** [comment]
> Thanks for fixing this @rajaths010494 . Looks good to me if the DAG runs all fine.

yes it ran fine for example dag

**Review by phanikumv — APPROVED** [review]

**Pull request merged**
