### PR TITLE
865 the hook needs to contain similar kwargs as the google providers

### PR DESCRIPTION
**Pull request by erdos2n**
I have added the `location` parameter in the hook. I do think this needs to get upgraded to integrate the `use_legacy_sql` parameter, as well, but that change may not be so simple given it could change the requirements.txt.

### CODE REVIEW

**Review by pankajastro — APPROVED** [review]
LGTM

**Comment by rajaths010494** [comment]
rebase once the PR gets merged https://github.com/astronomer/astronomer-providers/pull/867
and mypy issue should be resolved

**Comment by pankajastro** [comment]
FYI: Look like google async lib have some issue with no us location https://github.com/apache/airflow/issues/29307

**Comment by erdos2n** [comment]
One of the errors, currently, is a permission issue. It would make sense that it's a region issue, but I haven't verified for sure, since it's not my service-account. 

We should include this and just update the docs to reflect a possible issue with non-US locations.

**Comment by rajaths010494** [comment]
Can we fix the failing tests as well.

**Comment by erdos2n** [comment]
I've gone ahead and removed the `use_legacy_sql` kwarg from this PR since it was failing the tests. I think it's best to open another issue for this, as the current issue with the `location` kwarg is breaking a DAG for a customer. I will open a new, much more broad issue for update the `bigquery.py` file to meet the current kwargs of the provider package.

**Comment by rajaths010494** [comment]
Can you rebase the branch? There is mypy issues also

**Review by rajaths010494 — APPROVED** [review]

**Pull request merged**
