### PR TITLE
Add custom Sphinx extension to list available operators & sensors

### PR DESCRIPTION
**Pull request by pankajkoti**
The commit adds a custom Sphinx extension doing the following:
1. Walk the providers diretory and using ast.parse collect list of
   operators and sensors
2. Use raw HTML to generate tables for the above collected operators
   and sensors. Also, adds a link to the class definitions generated
   by URL construction.

### CODE REVIEW

**Comment by pankajkoti** [comment]
Screenshot 2022-07-08 at 6 06 34 PM

**Comment by pankajastro** [comment]
just curious, Do we have two tables one for operators and the other for sensors?

**Review by bharanidharan14 — APPROVED** [review]

**Comment by pankajkoti** [comment]
> just curious, Do we have two tables one for operators and the other for sensors?

yes, that's right. One for operator and another for sensors.

**Comment by pankajkoti** [comment]
Hi @kaxil I tried to use python code block with HTML but it is not supporting it as good as the native code-block directive provided by Sphinx. I tried various approaches but I'm stuck at dynamically populating rows for the `list-table` Sphinx directive by taking input from the custom extension. Perhaps, we need some templating but I would need some more time to explore that.
 
Following is the latest appearance with raw HTML (the Sphinx copy button does not apply to it as it is not a native Sphinx code block):
Screenshot 2022-07-11 at 4 03 57 PM

**Comment by kaxil** [comment]
> Hi @kaxil I tried to use python code block with HTML but it is not supporting it as good as the native code-block directive provided by Sphinx. I tried various approaches but I'm stuck at dynamically populating rows for the `list-table` Sphinx directive by taking input from the custom extension. Perhaps, we need some templating but I would need some more time to explore that.
> 
> Following is the latest appearance with raw HTML (the Sphinx copy button does not apply to it as it is not a native Sphinx code block): Screenshot 2022-07-11 at 4 03 57 PM

No worries, this is already good. Feel free to create a follow-up task on enhancing this, but that can be marked as low priority :)

**Comment by kaxil** [comment]
Just added the GitHub issue to this PR description :) 

In general, it is a good practise to include the GitHub issue that relates to this PR so that when the PR is merged, the ticket gets closed automatically as explained in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by kaxil** [comment]
Good work 👏

**Comment by pankajkoti** [comment]
> Just added the GitHub issue to this PR description :)
> 
> In general, it is a good practise to include the GitHub issue that relates to this PR so that when the PR is merged, the ticket gets closed automatically as explained in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Yes, thank you, have created a follow-up ticket: https://github.com/astronomer/astronomer-providers/issues/508

**Comment by jwitz** [comment]
This is awesome @pankajkoti !! Thank you so much!! I will update docs.astronomer.io to reference this page once it's generally available

**Comment by pankajkoti** [comment]
Thank you @jwitz . We will update you here once the new release goes through that includes this. :)

**Pull request merged**
