### PR TITLE
ci(github-actions): fix wrong variable used in test-rc workflow

### PR DESCRIPTION
**Pull request by Lee-W**
This is the root cause of the failure https://github.com/astronomer/astronomer-providers/actions/runs/5328666545/jobs/9653537662

### CODE REVIEW

**Review by pankajastro — APPROVED** [review]

**Review by pankajkoti — COMMENTED** [review]
Was the PR https://github.com/astronomer/astronomer-providers/pull/1194 created after this change? Mean to ask if we verified that our script works now? :)

**Comment by Lee-W** [comment]
No, we'll need to wait for tomorrow for it to run. Thus, I run the workflow manually with the branch created by the bot for testing it earlier.

**Comment by pankajkoti** [comment]
But tomorrow it won't run since we already have the branch/PR created now, right? 🤔

**Comment by Lee-W** [comment]
Ideally, yes; if not, then we have more fixes to go for the workflow 🤦‍♂️ So for actually test the full round, I think we'll need to wait for next provider release

**Comment by pankajkoti** [comment]
okay, understood, thank you! :)

**Comment by Lee-W** [comment]
Here's the pr for that fixing https://github.com/astronomer/astronomer-providers/pull/1207 🤦‍♂️

**Pull request merged**
