### PR TITLE
Fix Python3.11 constraints

### PR DESCRIPTION
**Pull request by pankajastro**
job: https://app.circleci.com/pipelines/github/astronomer/astronomer-providers/6270/workflows/9e4ee250-9b09-4512-a7a7-bb911e3b2cf9

### CODE REVIEW

**Review by pankajkoti — COMMENTED** [review]
I think with this we need to mention somewhere in our public docs that we don't support Hive provider with Python 3.11

**Comment by pankajastro** [comment]
> I think with this we need to mention somewhere in our public docs that we don't support Hive provider with Python 3.11

yes, good point. shall we add a note in readme?

**Comment by pankajastro** [comment]
> I think we could add this Hive provider limitation in our public doc limitations
> 
> https://astronomer-providers.readthedocs.io/en/stable/#limitations

This is README only, I have added in limitations section also and kept the note too because I feel that would be more visible

**Review by pankajkoti — APPROVED** [review]
Looks good to me after checks passing.

**Comment by pankajastro** [comment]
merging this one since currently main is broken but feel free to suggest any improvement

**Pull request merged**
