### PR TITLE
[DO NOT MERGE]:Test providers RC

### PR DESCRIPTION
**Pull request by phanikumv**

### CODE REVIEW

**Comment by phanikumv** [comment]
@pankajkoti can you check the mypy failures please.

**Comment by pankajkoti** [comment]
@phanikumv The changes made in https://github.com/astronomer/astronomer-providers/pull/784/commits/fcf7ffa300baec70813f1d9f40613ebd0c056a99 will solve the issue for mypy failure. We cannot add these changes now as the other PRs will break but we can add this as soon as the providers are released.

**Comment by pankajkoti** [comment]
@phanikumv can we close this PR?

**Comment by phanikumv** [comment]
Thanks @pankajkoti . Closing this

**Pull request closed without merging**
