### PR TITLE
Release 1.3.0

### LINKED ISSUE #314: Release activities for 1.3.0
Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.3.0

### PR DESCRIPTION
**Pull request by phanikumv**
Update `setup.cfg`, `docs/conf.py` and `CHANGELOG.rst` with the changes pertaining to release 1.3.0

Closes #314

### CODE REVIEW

**Review by kaxil — COMMENTED** [review]
I left some comments on https://github.com/astronomer/astronomer-providers/pull/290/ that needs to be addressed before we can release this.

We should probably publish a 1.3.0b1 version so we can test the beta directly as this one has some dependency and openlineage changes

**Comment by kaxil** [comment]
I have published 1.3.0b1 via https://github.com/astronomer/astronomer-providers/commit/f1be2f6d57a07e2e7116d593e7b8fba787219e3a to allow testing with Airflow 2.3 and new versions of the provider by running: `pip install astronomer-providers==1.3.0b1`

**Comment by pankajkoti** [comment]
> I left some comments on #290 that needs to be addressed before we can release this.
> 
> We should probably publish a 1.3.0b1 version so we can test the beta directly as this one has some dependency and openlineage changes

I will address these comments today and test out to see if it works well.

**Review by bharanidharan14 — COMMENTED** [review]
Conflicts Needs to be resolved

**Comment by pankajkoti** [comment]
> > I left some comments on #290 that needs to be addressed before we can release this.
> > We should probably publish a 1.3.0b1 version so we can test the beta directly as this one has some dependency and openlineage changes
> 
> I will address these comments today and test out to see if it works well.

I am seeing an issue on OpenLineage with the release version `0.8.1` and the draft PR https://github.com/astronomer/astronomer-providers/pull/331 to address the comments
cannot be merged until the we have a feedback on https://github.com/OpenLineage/OpenLineage/issues/736 .

**Comment by kaxil** [comment]
Created https://github.com/astronomer/astronomer-providers/pull/332 to unblock 1.3.0

**Review by bharanidharan14 — APPROVED** [review]

**Review by rajaths010494 — APPROVED** [review]

**Pull request merged**
